# Archivo de configuracion para el contador de varillas

# Configuraciones basicas
app_name: "Contador de varillas - IA+TECH"
version: test_operation_1920x1080_080425
debug_mode: False
generate_video: True
storage_data: False

model: "contador_yolo11n_040825.pt"
input_video: "rtsp://admin:Hik12345@192.168.18.5/Streaming/channels/101?transportmode=unicast"
# input_video: "rtsp://admin:IA+T3cCAM@192.168.18.3/Streaming/channels/101"
# input_video: "operation_1920x1080.mp4"
logo: "LOGO_CE.png"

folders:
  models: "models"
  media: "media"
  output: "output"
  assets: "assets"
  logger: "logger"
  storage: "storage"
  imgs: "imgs"

camera:
  # x_init: 1000
  # y_init: 1055
  # roi_width: 1548
  # roi_height: 1105
  # plot_x_offset: 300
  # plot_y_offset: 50
  # counter_init: 300
  # counter_end: 960
  # counter_line: 800
  # x_init: 650
  x_init: 600
  y_init: 280
  roi_width: 600
  roi_height: 800
  plot_x_offset: 300
  plot_y_offset: 50
  counter_init: 270
  counter_end: 500
  counter_line: 370

serial:
  port: "COM3"
  baud_rate: 115200
  timeout: 1

tracker:
  min_confidence: 0.8

actuator:
  x_offset: 50
  y_limit: 700
  y_init: 35
  y_finish: 560

test:
  image: "IMG_ContadorVarillas_00-05-57_7146.png"
  image2: "IMG_ContadorVarillas_00-05-48_6972.png"